"""
Phase 2: Pretrain T2/S2 backbone on Do ∪ Dl (optical + few-shot SAR).

This trains a standard Faster R-CNN + ResNet-101 + FPN on the combined
optical + labeled SAR dataset. The key purpose is to give T2/S2 cross-domain
knowledge BEFORE the semi-supervised dual teacher training begins.

This is a critical difference from our previous FCOS implementation:
the paper's T2/S2 learns "what a ship looks like" from BOTH domains first.

Usage:
    python tools/train.py configs/phase2_pretrain_optical_sar.py \
        --cfg-options fold=1 percent=3
"""

_base_ = [
    # 部署时将本文件放入 dual_teacher_repo/configs/reproduce/ 目录下
    "../baseline/base.py",
]

# ============================================================
# Model: Faster R-CNN + ResNet-101 (caffe) + FPN
# ============================================================
model = dict(
    backbone=dict(
        depth=101,
        norm_cfg=dict(requires_grad=False),
        norm_eval=True,
        style="caffe",
        init_cfg=dict(
            type="Pretrained",
            checkpoint="open-mmlab://detectron2/resnet101_caffe",
        ),
    ),
    roi_head=dict(
        bbox_head=dict(num_classes=1),
    ),
)

# ============================================================
# Z-score normalization
# ============================================================
img_norm_cfg = dict(
    mean=[103.530, 116.280, 123.675],
    std=[1.0, 1.0, 1.0],
    to_rgb=False,
)

# ============================================================
# Dataset: Do ∪ Dl (ShipRSImageNet optical + few-shot SSDD SAR)
# ============================================================
# The annotation file is generated by prepare_data.py step 4.
# It concatenates optical images with `percent` labeled SAR images.
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        _delete_=True,
        type="CocoDataset",
        classes=("ship",),
        ann_file="data/optical_ssdd/annotations/"
                 "instances_train2017.${fold}@${percent}_dior_annotations.json",
        # 统一图像目录 (由 setup_phase2_images.py 生成)
        img_prefix="data/optical_ssdd/images/",
        pipeline=[
            dict(type="LoadImageFromFile"),
            dict(type="LoadAnnotations", with_bbox=True),
            dict(
                type="Resize",
                img_scale=[(1333, 400), (1333, 1200)],
                multiscale_mode="range",
                keep_ratio=True,
            ),
            dict(type="RandomFlip", flip_ratio=0.5),
            dict(type="Normalize", **img_norm_cfg),
            dict(type="Pad", size_divisor=32),
            dict(type="DefaultFormatBundle"),
            dict(type="Collect", keys=["img", "gt_bboxes", "gt_labels"]),
        ],
    ),
    val=dict(
        type="CocoDataset",
        classes=("ship",),
        ann_file="data/ssdd/annotations/test.json",
        img_prefix="data/ssdd/test_images/",
        pipeline=[
            dict(type="LoadImageFromFile"),
            dict(
                type="MultiScaleFlipAug",
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type="Resize", keep_ratio=True),
                    dict(type="RandomFlip"),
                    dict(type="Normalize", **img_norm_cfg),
                    dict(type="Pad", size_divisor=32),
                    dict(type="ImageToTensor", keys=["img"]),
                    dict(type="Collect", keys=["img"]),
                ],
            ),
        ],
    ),
    test=dict(
        type="CocoDataset",
        classes=("ship",),
        ann_file="data/ssdd/annotations/test.json",
        img_prefix="data/ssdd/test_images/",
    ),
)

# ============================================================
# Training schedule
# ============================================================
# Slightly longer than Phase 1 since we have mixed domains
optimizer = dict(type="SGD", lr=0.01, momentum=0.9, weight_decay=0.0001)
lr_config = dict(step=[2000, 2500])
runner = dict(type="IterBasedRunner", max_iters=2800)
checkpoint_config = dict(by_epoch=False, interval=500, max_keep_ckpts=5)
evaluation = dict(interval=500, metric="bbox")

# ============================================================
# Output
# ============================================================
work_dir = "work_dirs/phase2_pretrain_optical_sar/${percent}/${fold}"
log_config = dict(
    interval=50,
    hooks=[dict(type="TextLoggerHook", by_epoch=False)],
)
